name: Build and Release Signed APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Version Code
        run: |
          NOW=$(date +%s)
          # 2026/02/13 11:17
          START_DATE=1770944810
          VERSION_CODE=$(( ($NOW - $START_DATE) / 60 ))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Decode Keystore
        run: |
          # decode secret Base64 to app/vtl-android-keystore.jks
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > app/vtl-android-keystore.jks

      - name: Build Signed APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.versionCode=${{ env.VERSION_CODE }} \
            -Pandroid.injected.versionName=${{ github.ref_name }}
        env:
          MYAPP_RELEASE_STORE_FILE: vtl-android-keystore.jks
          MYAPP_RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          MYAPP_RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          mkdir -p release-artifacts
          cp app/build/outputs/apk/release/app-release.apk release-artifacts/JaviCalendar_${{ github.ref_name }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/JaviCalendar_${{ github.ref_name }}.apk
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ### ðŸ“¦ Release Notes
            - **App:** JaviCalendar
            - **Version Name:** ${{ github.ref_name }}
            - **Version Code:** ${{ env.VERSION_CODE }}
            - **Build Time:** $(date +'%Y-%m-%d %H:%M:%S')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}